# Generated by Django 6.0.1 on 2026-01-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_contact_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('resume_text', models.TextField()),
                ('target_region', models.CharField(default='Ontario', max_length=255)),
                ('profession', models.CharField(default='Doctor', max_length=255)),
                ('readiness_score', models.IntegerField(blank=True, null=True)),
                ('is_fast_track_eligible', models.BooleanField(default=False)),
                ('audit_report_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
